### ISSUE TITLE
作者你好，我是做点云压缩的，希望可以参考您的代码，不知道您的代码什么时候会上传呢？

### ISSUE THREAD

**Issue by njnf66** [gbliao/TDRNet#1]
作者你好，我是做点云压缩的，最近读了您的论文，希望可以参考您的Dual-Branch Restoration模块，但是发现您只上传了readme文件，不知道您的代码什么时候会上传呢？

**Comment by gbliao** [comment]
Thank you for your interest. Codes will be released as soon as possible.

**Comment by njnf66** [comment]
好的。祝您学业顺利。

**Comment by njnf66** [comment]
Hello, author, your Baidu internet link verification code seems to be wrong, I can't open it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月2日(星期四) 下午4:35
收件人: ***@***.***&gt;; 
抄送: "ٺ享 ε 空 ...***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gbliao/TDRNet] 作者你好，我是做点云压缩的，希望可以参考您的代码，不知道您的代码什么时候会上传呢？ (Issue #1)














 
Closed #1 as completed.

**Comment by gbliao** [comment]
> Hello, author, your Baidu internet link verification code seems to be wrong, I can't open it.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年5月2日(星期四) 下午4:35 收件人: ***@***.***&gt;; 抄送: "ٺ享 ε 空 ...***@***.***&gt;; ***@***.***&gt;; 主题: Re: [gbliao/TDRNet] 作者你好，我是做点云压缩的，希望可以参考您的代码，不知道您的代码什么时候会上传呢？ (Issue #1) Closed #1 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Please open the following link: https://pan.baidu.com/s/1qUB0nkjZEbqvPs5h-cgNzg?pwd=7sj8 
Code：7sj8

**Comment by njnf66** [comment]
I have got it, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gbliao/TDRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月2日(星期四) 下午4:55
***@***.***&gt;;
抄送:&nbsp;"ٺ享 ε 空 ...***@***.******@***.***&gt;;
主题:&nbsp;Re: [gbliao/TDRNet] 作者你好，我是做点云压缩的，希望可以参考您的代码，不知道您的代码什么时候会上传呢？ (Issue #1)





  
Hello, author, your Baidu internet link verification code seems to be wrong, I can't open it.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年5月2日(星期四) 下午4:35 收件人: @.&gt;; 抄送: "ٺ享 ε 空 ...@.&gt;; @.&gt;; 主题: Re: [gbliao/TDRNet] 作者你好，我是做点云压缩的，希望可以参考您的代码，不知道您的代码什么时候会上传呢？ (Issue #1) Closed #1 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Please open the following link: https://pan.baidu.com/s/1qUB0nkjZEbqvPs5h-cgNzg?pwd=7sj8
 Code：7sj8
